### ISSUE TITLE
Feature Request: Add configuration option for data persistance

### ISSUE THREAD

**Issue by lumattr** [localstack/localstack-docker-extension#12]
At the moment none of the data is persisted so i lose my resources if the container restart or if my laptop restarts. 

Please could you provide a configuration or document an option if one already exists.

version : 1.3.1.dev

**Comment by Pive01** [comment]
> At the moment none of the data is persisted so i lose my resources if the container restart or if my laptop restarts.
> 
> Please could you provide a configuration or document an option if one already exists.
> 
> version : 1.3.1.dev

Have you tried using the latest image of the extension? This should be already fixed

**Comment by Pive01** [comment]
Closing as already resolved in prevoius version
