### ISSUE TITLE
Bug: Extension does not start up with error "locating users: using /tmp as mount point"

### ISSUE THREAD

**Issue by Cliftonz** [localstack/localstack-docker-extension#22]
On Windows 11, I am receiving the following error:
``` Error while locating users: using /tmp as mount point ```

Feel free to ask if you need more details or are able to provide how to get a more detailed log of the error.

**Comment by Pive01** [comment]
Hi @Cliftonz , thanks for your report.
This is a known issue and we are working to solve it. In the meantime, you should still be able to launch localstack from the extension but unfortunately some features may not be working.

**Comment by gskoczylas** [comment]
> On Windows 11, I am receiving the following error:
> `Error while locating users: using /tmp as mount point`

FYI: On Windows 10, I am receiving the same error.
