### ISSUE TITLE
User not available when configuring default mount point settings

### ISSUE THREAD

**Issue by cedric-fauth** [localstack/localstack-docker-extension#31]
## Describe the bug
I installed the extension and now I need to set `Default mount point settings`. I am using Ubuntu WSL but no User is shown.

## Screenshots

![image](https://user-images.githubusercontent.com/105929519/228231178-63d1fb60-39e8-4775-8a6b-b207a83315c7.png)

**Comment by Pive01** [comment]
Hi @cedric-fauth thank for reporting this issue. Can you try executing `dir \\wsl.localhost\Ubuntu\home` in the windows powershell and report back the output?

**Comment by Pive01** [comment]
> ```
> Mode                 LastWriteTime         Length Name
> ----                 -------------         ------ ----
> d-----        28.10.2022     14:26                vscode
> d-----        26.09.2022     12:34                user1
> d-----        29.03.2023     15:08                user2
> ```


Thanks, I think I got why It's not working for you; we'll release a fix soon
