### ISSUE TITLE
Update images pulls non-existing and deprecated images

### ISSUE THREAD

**Issue by joe4dev** [localstack/localstack-docker-extension#37]
## Describe the bug
Similar to the LocalStack CLI https://github.com/localstack/localstack/issues/8178, the "Update images" functionality pulls non-existing and deprecated images.

## Steps to Reproduce
1. Click on '..."
2. Click on 'Update images'
3. Click on 'Update'

<details>
<summary>Click to toggle full list of images</summary>

```
Updating docker images


✅ Image localstack/localstack-pro:latest up-to-date.


❌ Image public.ecr.aws/lambda/nodejs:18-rapid-x86_64 pull failed: Error during the communication with the docker daemon


✅ Image localstack/localstack:latest up-to-date.


❌ Image public.ecr.aws/lambda/python:3.9-rapid-x86_64 pull failed: Error during the communication with the docker daemon


✅ Image mlupin/docker-lambda:python3.9 up-to-date.


✅ Image mlupin/docker-lambda:nodejs16.x up-to-date.


✅ Image mlupin/docker-lambda:nodejs14.x up-to-date.


✅ Image public.ecr.aws/lambda/go:1 up-to-date.


✅ Image public.ecr.aws/lambda/java:8.al2 up-to-date.


✅ Image public.ecr.aws/lambda/python:3.8 up-to-date.


✅ Image public.ecr.aws/lambda/dotnet:core3.1 up-to-date.


✅ Image public.ecr.aws/lambda/java:8 up-to-date.


✅ Image public.ecr.aws/lambda/dotnet:6 up-to-date.


✅ Image public.ecr.aws/lambda/java:11 up-to-date.


✅ Image public.ecr.aws/lambda/python:3.9-x86_64 up-to-date.


✅ Image public.ecr.aws/lambda/python:3.9 up-to-date.


✅ Image public.ecr.aws/lambda/python:3.7 up-to-date.


✅ Image public.ecr.aws/lambda/ruby:2.7 up-to-date.


✅ Image public.ecr.aws/lambda/provided:alami up-to-date.


✅ Image public.ecr.aws/lambda/nodejs:18-x86_64 up-to-date.


✅ Image public.ecr.aws/lambda/nodejs:18 up-to-date.


✅ Image public.ecr.aws/lambda/nodejs:14 up-to-date.


✅ Image public.ecr.aws/lambda/nodejs:16 up-to-date.


✅ Image public.ecr.aws/lambda/nodejs:12 up-to-date.


✅ Image public.ecr.aws/lambda/provided:al2 up-to-date.


✅ Image localstack/localstack-pro:2.0 up-to-date.


✅ Image localstack/localstack-pro:2.0.1 up-to-date.


✅ Image localstack/localstack-docker-desktop:0.4.0 up-to-date.


✅ Image localstack/localstack-pro:1.4.0 up-to-date.


✅ Image localstack/localstack-docker-desktop:0.3.1 up-to-date.


✅ Image localstack/bigdata:latest up-to-date.


✅ Image localstack/lambda:nodejs14.x up-to-date.


✅ Image localstack/lambda:python3.9 up-to-date.


✅ Image localstack/lambda:provided.al2 up-to-date.


✅ Image localstack/lambda:java11 up-to-date.


✅ Image lambci/lambda:java11 up-to-date.


✅ Image lambci/lambda:java8.al2 up-to-date.


✅ Image lambci/lambda:ruby2.7 up-to-date.


✅ Image lambci/lambda:nodejs12.x up-to-date.


✅ Image lambci/lambda:java8 up-to-date.


✅ Image lambci/lambda:go1.x up-to-date.




Images updated: 0, Images failed: 2, total images processed: 41.
```
</details>

## Expected behavior
Just pull existing and non-deprecated images. See https://github.com/localstack/localstack/issues/8178 for details.

## Screenshots
<img width="580" alt="Screenshot 2023-04-28 at 09 39 53" src="https://user-images.githubusercontent.com/8161292/235086805-325f9c7f-447f-4508-a832-fc18609a192f.png">

## Additional context

**Architecture suffix**
Images with an architecture suffix (e.g., `-x86_64`) can be removed because multi-architecture manifests use the same image name rather than suffixes.

**Architecture sidenote**
On ARM macs supporting x86_64 emulation, downloading all Lambda images might fetch a lot of arm64 images although Lambda mostly runs on emulated x86_64 unless deploying arm64 Lambdas specifically or setting LAMBDA_IGNORE_ARCHITECTURE=1.

**nit: Preview only shows a subset**
<img width="679" alt="Screenshot 2023-04-28 at 09 47 50" src="https://user-images.githubusercontent.com/8161292/235087255-2a026e04-000e-4641-9dfb-243cdd58c01d.png">

**Comment by alexrashed** [comment]
I think this issue should already be resolved.
The extension does not define the list of images itself (but uses the LocalStack CLI under the hood), so https://github.com/localstack/localstack/issues/8178 should have also fixed this one.
@joe4dev could you maybe check if this is the case / if this ticket can already be closed?

**Comment by joe4dev** [comment]
Thanks for the reminder @alexrashed 

Yes, this is looking good enough 👍 I can confirm this is fixed with https://github.com/localstack/localstack/issues/8178



<img width="523" alt="Screenshot 2023-08-11 at 13 13 29" src="https://github.com/localstack/localstack-docker-extension/assets/8161292/e6523282-2940-41d9-80a9-93c51c134bc3">
