### ISSUE TITLE
Add ability to customize image tag for LS container

### ISSUE THREAD

**Issue by whummer** [localstack/localstack-docker-extension#45]
## Summary

Currently we're hardcoding the version 2.1.0 for the Docker image used to spin up the container. 
https://github.com/localstack/localstack-docker-extension/blob/6740c80f35a2e1916bcc73a4c06e07cc9dda69a7/ui/src/constants/common.ts#L3

Would be great if there was an easy way to configure that, or at least not hardcode 2.1.0 and use `latest` instead. 

It is actually possible to customize the image name/version via `IMAGE_NAME`:

<img width="619" alt="image" src="https://github.com/localstack/localstack-docker-extension/assets/2807888/d75f0e53-b12f-41f3-b3ed-00afbe98e905">

Perhaps we could simply use the `latest` tag for now, as a quick workaround?

/cc @Pive01 @HarshCasper

**Comment by Pive01** [comment]
That's just the image to spawn the cli, it should start latest nevertheless when you click the start button. This was as results of version 2.2 I believe, released on late July that introduced this `machine.json` file that was causing problems so pinning the versioin of the cli to 2.1 was the quickest way me and Thomas came up with @whummer

**Comment by whummer** [comment]
Thanks for clarifying @Pive01 - looks like we can close the issue in that case 👍 . Maybe in a future iteration we can try to upgrade the CLI container to a more recent version, as there may be new configuration flags coming in (e.g., related to DNS, networking, etc). But not super urgent right now.
